### PR TITLE
Excecute on any non entry_point less file

### PR DESCRIPTION
**Pull request by luisvt**
Change transformer logic to process less files on any change that has not been done in entry_points. In this way, if we modify a less file that is not entry_point, the transformer is executed. However only
entry_point files are transpiled to css.

### CODE REVIEW

**Comment by AdalbertoLacruz** [comment]
Thanks for the logic to use the aggregate transformer. Your modifications are the base for the reshaped transformer.

Could you try the new transformer before release to pub. As the Readme says, it support default values for .less and .html files, and \* in the entry_points, and ! as exclusion path.

**Comment by luisvt** [comment]
Hello, It is not working as I expect. For example I have this project:

https://github.com/luisvt/bootstrap_elements

and I have `lib/less/boostrap.less` as my entry_point. So what I was supposing is that only this file is going to be processed. However whenever I made a change in other files, for example `lib/less/alert.less` I want that the transformer process again `bootstrap.less` file since it is my entry_point. With the transformer in the way that you have it right now only listen on changes of entry_points, dependent files are not being listened.

I added some changes so you can test it.

**Comment by AdalbertoLacruz** [comment]
OK. I'll look for it.

**Comment by AdalbertoLacruz** [comment]
Based on your files I have done some changes:
- classifyPrimary returns all under the same key, so a .less change affects also the .html dependents.
- We don't need to check `options.entry_points.isEmpty`, because in that case, it get default values (*.less, *.html).
- I haven't the transformer double execution problem (?).
- In my tests, a .less file change trigger the transformer as you request.
- I was trying some optimizations, but are not clear. In the transformer execution, we must deliver, by example, the file.css even if the file.less and dependents don't have any changes. The only easy optimization is to keep the css/html result in a cache and don't compile if we don't have any changes. But the memory/time trade don't pay.

**Comment by luisvt** [comment]
It works as I expect. Thanks for the changes.
- The transformer double execution maybe is caused because I'm working on linux.
- I don't understand what do you mean with optimization. I know that when I import the same file many times in difierent files, the compiler get slow, but that's for other ticket.

**Comment by AdalbertoLacruz** [comment]
Optimization was a try to minimize the number of files processed.

**Pull request closed without merging**
